# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20170311_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
