# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
