# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-16 01:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20170406_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default='', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a la fuente de la imagen'),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='place',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Página web'),
        ),
    ]
