# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 23:28
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20180415_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='city',
            name='image_source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a la fuente de la imagen'),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
