# Generated by Django 2.0.13 on 2019-06-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20190621_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name='Nombre'
            ),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name='Nombre'
            ),
        ),
    ]
