# Generated by Django 2.0.13 on 2020-02-29 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0010_auto_20190621_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='editors',
            field=models.ManyToManyField(related_name='can_edit_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
    ]
