# Generated by Django 4.2.11 on 2024-03-18 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0011_auto_20200229_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterField(
            model_name='place',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='can_edit_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
