# Generated by Django 4.2.11 on 2024-03-19 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_place_options_alter_place_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='places.city', verbose_name='Ciudad'),
        ),
    ]
