# Generated by Django 5.1.7 on 2025-03-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_place_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='show_on_home',
        ),
    ]
