# Generated by Django 5.1.9 on 2025-06-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0014_remove_city_show_on_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Enlace a la fuente de la imagen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="place",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Enlace a la fuente de la imagen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="place",
            name="website_url",
            field=models.URLField(blank=True, default="", verbose_name="Página web"),
            preserve_default=False,
        ),
    ]
