# Generated by Django 5.1.9 on 2025-08-30 17:32
from io import StringIO
from html.parser import HTMLParser

from django.db import migrations


# From https://stackoverflow.com/a/925630/914332
class MLStripper(HTMLParser):
    """Strip HTML tags"""
    def __init__(self):
        super().__init__()
        self.reset()
        self.strict = False
        self.convert_charrefs= True
        self.text = StringIO()

    def handle_data(self, d):
        self.text.write(d)

    def get_data(self):
        return self.text.getvalue()


def update_description(apps, schema_editor):
    # Strip HTML from description and reduce length to 500 characters
    Place = apps.get_model("places", "Place")
    for place in Place.objects.all():
        if place.address:
            s = MLStripper()
            s.feed(place.address)

            place.description = s.get_data()[:100]
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0015_alter_city_image_source_url_and_more"),
    ]

    operations = [
        migrations.RunPython(update_description),
    ]
