# Generated by Django 5.1.9 on 2025-08-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0016_auto_20250830_1232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Dirección"),
        ),
    ]
