# Generated by Django 5.1.9 on 2025-08-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0017_alter_place_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="description",
            new_name="address",
        ),
    ]
