# Generated by Django 5.1.9 on 2025-08-31 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0018_rename_description_place_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ("name",),
                "verbose_name": "Ciudad",
                "verbose_name_plural": "Ciudades",
            },
        ),
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="Dirección",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=255,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
                verbose_name="Nombre",
            ),
        ),
    ]
