# Generated by Django 5.1.9 on 2025-06-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userbadge_badge_alter_userbadge_user_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="userbadge",
        #     name="badge",
        # ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="user",
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.DeleteModel(
            name="UserBadge",
        ),
    ]
