# Generated by Django 4.2.11 on 2024-03-25 02:59

from django.db import migrations
from django.contrib.auth import get_user_model


def migrate_username_to_email(apps, schema_editor):
    User = get_user_model()
    for user in User.objects.all():
        user.username = user.email
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userbadge_badge_alter_userbadge_user_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_username_to_email),
    ]
