# Generated by Django 4.2.11 on 2024-03-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_migrate_username_to_email'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[('CREATE TABLE users_user AS TABLE auth_user WITH NO DATA;')],
            reverse_sql=[('DROP TABLE users_user;')],
        )
    ]
