# Generated by Django 5.1.9 on 2025-09-28 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_remove_userbadge_badge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("event_creation_quota", models.PositiveIntegerField(default=10)),
                ("organizer_creation_quota", models.PositiveIntegerField(default=5)),
                ("speaker_creation_quota", models.PositiveIntegerField(default=5)),
                ("place_creation_quota", models.PositiveIntegerField(default=5)),
                ("quota_period_seconds", models.PositiveIntegerField(default=86400)),
            ],
        ),
    ]
