# Generated by Django 5.1.9 on 2025-09-28 01:09

from django.db import migrations
from django.conf import settings


def create_user_settings(apps, schema_editor):
    """
    Create UserSettings for all existing users without one.
    """
    # Use the actual user model defined in settings.AUTH_USER_MODEL
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserSettings = apps.get_model("users", "UserSettings")

    for user in User.objects.all():
        UserSettings.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usersettings"),
    ]

    operations = [
        migrations.RunPython(create_user_settings, migrations.RunPython.noop),
    ]
