# Generated by Django 4.2.11 on 2024-03-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_create_new_users_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[('INSERT INTO users_user SELECT * FROM auth_user;')],
            reverse_sql=[('TRUNCATE users_user')],
        )
    ]
