# Generated by Django 4.2.11 on 2024-03-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_copy_data_to_new_users_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'CREATE TABLE users_user_groups AS TABLE auth_group WITH NO DATA; '
                'INSERT INTO users_user_groups SELECT * FROM auth_group;'
            ],
            reverse_sql=['DROP TABLE users_user_groups;'],
        ),
    ]
