# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 02:05
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'event_type',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Lecture'),
                            (2, 'Master class'),
                            (3, 'Excursion'),
                            (4, 'Show'),
                            (5, 'Round table'),
                            (6, 'Conference'),
                            (7, 'Meeting'),
                            (8, 'Debate'),
                        ]
                    ),
                ),
                (
                    'topic',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Design'),
                            (2, 'City'),
                            (3, 'Science'),
                            (4, 'Art'),
                            (5, 'Business'),
                            (6, 'Society'),
                            (7, 'Technology'),
                            (8, 'Media'),
                            (9, 'Culture'),
                            (10, 'Photography'),
                            (11, 'Cinema'),
                        ]
                    ),
                ),
                ('event_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField(null=True)),
                (
                    'price',
                    models.DecimalField(decimal_places=2, default=0, max_digits=9),
                ),
                ('image', models.ImageField(null=True, upload_to='')),
                ('organizer', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'place',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='places.Place'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
