# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170305_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('event_date',)},
        ),
        migrations.AddField(
            model_name='event',
            name='event_source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Public lecture'), (2, 'Debate'), (3, 'Master class'), (4, 'Tour'), (5, 'Meeting'), (6, 'Theatrical play'), (7, 'Concert'), (8, 'Seminar')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.PositiveSmallIntegerField(choices=[(1, 'City'), (2, 'Science'), (3, 'Art'), (4, 'Business'), (5, 'Society'), (6, 'Human Science'), (7, 'Languages'), (8, 'Literature'), (9, 'Environment'), (10, 'Medicine')]),
        ),
    ]
