# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_organizer_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organizers'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='image_source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
