# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 23:32
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170406_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                default=True, editable=False, populate_from='name', unique=True
            ),
            preserve_default=False,
        ),
    ]
