# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 02:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_socialnetworkpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetworkpost',
            options={'ordering': ('-published_at',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(
                help_text='Por favor, asegúrese de que el organizador que quiere asignar al evento no existe en nuestro sistema, antes de crearlo.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='events.Organizer',
                verbose_name='Organizador',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(
                help_text='Por favor, asegúrese de que el lugar que quiere asignar al evento no existe en nuestro sistema, antes de crearlo.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='places.Place',
                verbose_name='Lugar',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(
                blank=True,
                help_text='Por favor, asegúrese de que el presentador/la presentadora que quiere asignar al evento no existe en nuestro sistema, antes de crearlo/crearla.',
                related_name='events',
                to='events.Speaker',
                verbose_name='Presentadores',
            ),
        ),
        migrations.AlterField(
            model_name='socialnetworkpost',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='social_posts',
                to='events.Event',
            ),
        ),
    ]
