# Generated by Django 2.0.13 on 2019-03-25 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20181117_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='Por favor, asegúrese de que el organizador que quiere asignar al evento no existe en nuestro sistema, antes de crearlo.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='events.Organizer', verbose_name='Organizador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(help_text='Por favor, asegúrese de que el lugar que quiere asignar al evento no existe en nuestro sistema, antes de crearlo.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='places.Place', verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialnetworkpost',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialnetworkpost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='social_posts', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
