# Generated by Django 2.0.13 on 2019-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_pressarticle_publication_date'),
        ('events', '0014_auto_20190325_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='press_articles',
            field=models.ManyToManyField(blank=True, related_name='events', to='news.PressArticle', verbose_name='Artículos e prensa'),
        ),
    ]
