# Generated by Django 2.0.13 on 2019-06-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20190616_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha final'),
        ),
    ]
