# Generated by Django 2.0.13 on 2019-06-22 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20190621_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(related_name='events', to='events.Organizer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(help_text='Por favor, asegúrese de que el organizador que quiere asignar al evento no existe en nuestro sistema, antes de crearlo.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='events.Organizer', verbose_name='Organizador'),
        ),
    ]
