# Generated by Django 2.0.13 on 2019-06-22 02:12

from django.db import migrations


def make_many_organizers(apps, schema_editor):
    """
        Adds the Organizer object in Event.organizer to the
        many-to-many relationship in Event.organizers
    """
    Event = apps.get_model('events', 'Event')

    for event in Event.objects.all():
        event.organizers.add(event.organizer)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20190621_2111'),
    ]

    operations = [
        migrations.RunPython(make_many_organizers),
    ]
