# Generated by Django 2.0.13 on 2019-06-22 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20190621_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(
                blank=True,
                help_text='Por favor, asegúrese de que el organizador que quiere asignar al evento no existe en nuestro sistema, antes de crearlo.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='event',
                to='events.Organizer',
                verbose_name='Organizador',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(
                help_text='Por favor, asegúrese de que el organizador que quiere asignar al evento no existe en nuestro sistema, antes de crearlo.',
                related_name='events',
                to='events.Organizer',
                verbose_name='Organizadores',
            ),
        ),
    ]
