# Generated by Django 2.0.13 on 2019-06-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20190621_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
