# Generated by Django 2.0.13 on 2019-07-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Conferencia pública'), (2, 'Debate'), (3, 'Taller'), (4, 'Recorrido'), (5, 'Encuentro'), (6, 'Obra de teatro'), (7, 'Concierto'), (8, 'Seminario'), (9, 'Exposición'), (10, 'Festival'), (11, 'Cine')], null=True, verbose_name='Tipo del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Urbanismo'), (2, 'Ciencias exactas'), (3, 'Arte'), (4, 'Emprendimiento'), (5, 'Democracia'), (6, 'Ciencias humanas'), (7, 'Idiomas'), (8, 'Literatura'), (9, 'Medioambiente'), (10, 'Medicina')], null=True, verbose_name='Tema'),
        ),
    ]
