# Generated by Django 2.0.13 on 2019-11-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20190722_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Página en Facebook'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Página en Instagram'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Página en Twitter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(db_index=True, help_text='p. ej. 23/11/2019 16:40', verbose_name='Fecha del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='p. ej. 23/11/2019 18:00 (opcional)', null=True, verbose_name='Fecha final'),
        ),
    ]
