# Generated by Django 2.0.13 on 2020-02-29 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0024_auto_20191103_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='can_edit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizer',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='can_edit_organizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speaker',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='can_edit_speakers', to=settings.AUTH_USER_MODEL),
        ),
    ]
