# Generated by Django 4.2.11 on 2024-03-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20200229_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={
                'ordering': ['name'],
                'verbose_name': 'Presentador',
                'verbose_name_plural': 'Presentadores',
            },
        ),
    ]
