# Generated by Django 5.1.7 on 2025-03-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_remove_event_press_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='filbo_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ID del FILBo'),
        ),
    ]
