# Generated by Django 5.1.7 on 2025-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_filbo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_source_url',
            field=models.URLField(max_length=500, null=True, verbose_name='Enlace a la página del evento'),
        ),
    ]
