# Generated by Django 5.1.7 on 2025-04-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_event_event_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured_on_homepage',
            field=models.BooleanField(
                default=False, verbose_name='Está destacado en la página principal'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, 'Urbanismo'),
                    (2, 'Ciencia'),
                    (3, 'Arte'),
                    (4, 'Emprendimiento'),
                    (5, 'Democracia'),
                    (6, 'Ciencias humanas'),
                    (7, 'Idiomas'),
                    (8, 'Libros'),
                    (9, 'Medio ambiente'),
                    (10, 'Salud'),
                ],
                null=True,
                verbose_name='Tema',
            ),
        ),
    ]
