# Generated by Django 5.1.9 on 2025-06-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_event_is_featured_on_homepage_alter_event_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_source_url",
            field=models.URLField(
                default="", max_length=500, verbose_name="Enlace a la página del evento"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Créditos/atribución de la imagen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizer",
            name="facebook_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Página en Facebook"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizer",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Enlace a la fuente de la imagen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizer",
            name="instagram_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Página en Instagram"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizer",
            name="twitter_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Página en Twitter"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizer",
            name="website_url",
            field=models.URLField(blank=True, default="", verbose_name="Página web"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="speaker",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Enlace a la fuente de la imagen"
            ),
            preserve_default=False,
        ),
    ]
