# Generated by Django 5.1.9 on 2025-06-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0031_alter_event_event_source_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("literature", "Literatura"),
                    ("society", "Sociedad"),
                    ("environment", "Medio ambiente"),
                    ("science", "Ciencia"),
                    ("art", "Arte"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
