# Generated by Django 5.1.9 on 2025-06-03 00:00

from django.db import migrations

EVENT_TYPE_PUBLIC_LECTURE = 1
EVENT_TYPE_THEATRICAL_PLAY = 6
EVENT_TYPE_CONCERT = 7
EVENT_TYPE_EXHIBITION = 9
EVENT_TYPE_FESTIVAL = 10
EVENT_TYPE_MOVIES = 11

EVENT_TOPIC_CITY = 1
EVENT_TOPIC_SCIENCE = 2
EVENT_TOPIC_ART = 3
EVENT_TOPIC_BUSINESS = 4
EVENT_TOPIC_SOCIETY = 5
EVENT_TOPIC_HUMAN_SCIENCE = 6
EVENT_TOPIC_LANGUAGES = 7
EVENT_TOPIC_BOOKS = 8
EVENT_TOPIC_ENVIRONMENT = 9
EVENT_TOPIC_HEALTH = 10

EVENT_CATEGORY_LITERATURE = "literature"
EVENT_CATEGORY_SOCIETY = "society"
EVENT_CATEGORY_ENVIRONMENT = "environment"
EVENT_CATEGORY_SCIENCE = "science"
EVENT_CATEGORY_ART = "art"


def migrate_categories(apps, schema_editor):
    # We can't import the Event model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        if event.topic in [
            EVENT_TOPIC_CITY,
            EVENT_TOPIC_BUSINESS,
            EVENT_TOPIC_SOCIETY,
            EVENT_TOPIC_HUMAN_SCIENCE,
            EVENT_TOPIC_LANGUAGES,
            EVENT_TOPIC_HEALTH,
        ]:
            event.category = EVENT_CATEGORY_SOCIETY
        elif event.topic == EVENT_TOPIC_SCIENCE:
            event.category = EVENT_CATEGORY_SCIENCE
        elif event.topic == EVENT_TOPIC_ART:
            event.category = EVENT_CATEGORY_ART
        elif event.topic == EVENT_TOPIC_BOOKS:
            event.category = EVENT_CATEGORY_LITERATURE
        elif event.topic == EVENT_TOPIC_ENVIRONMENT:
            event.category = EVENT_CATEGORY_ENVIRONMENT
        elif event.event_type in [
            EVENT_TYPE_THEATRICAL_PLAY,
            EVENT_TYPE_CONCERT,
            EVENT_TYPE_MOVIES,
            EVENT_TYPE_FESTIVAL,
            EVENT_TYPE_EXHIBITION,
        ]:
            event.category = EVENT_CATEGORY_ART
        elif 'libro' in event.title.lower():
            event.category = EVENT_CATEGORY_LITERATURE
        elif 'literatura' in event.title.lower():
            event.category = EVENT_CATEGORY_LITERATURE
        elif 'concierto' in event.title.lower():
            event.category = EVENT_CATEGORY_ART
        elif 'musical' in event.title.lower():
            event.category = EVENT_CATEGORY_ART
        elif 'música' in event.title.lower():
            event.category = EVENT_CATEGORY_ART
        elif 'musica' in event.title.lower():
            event.category = EVENT_CATEGORY_ART
        elif 'teatro' in event.title.lower():
            event.category = EVENT_CATEGORY_ART
        elif 'poesía' in event.title.lower():
            event.category = EVENT_CATEGORY_LITERATURE
        elif 'poesia' in event.title.lower():
            event.category = EVENT_CATEGORY_LITERATURE
        elif 'ciencia ficción' in event.title.lower():
            event.category = EVENT_CATEGORY_LITERATURE
        elif event.filbo_id:
            event.category = EVENT_CATEGORY_LITERATURE
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0032_event_category"),
    ]

    operations = [
        migrations.RunPython(migrate_categories),
    ]
