# Generated by Django 5.1.9 on 2025-08-31 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0034_remove_event_event_type_remove_event_topic"),
        ("places", "0019_alter_city_options_alter_place_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_end_date",
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(default="", verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                help_text="Por favor asegúrate de que el organizador que deseas asignar al evento no exista en nuestro sistema antes de crearlo",
                related_name="events",
                to="events.organizer",
                verbose_name="Organizadores",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.ForeignKey(
                help_text="Por favor asegúrate de que el lugar que deseas asignar al evento no exista en nuestro sistema antes de crearlo",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="places.place",
                verbose_name="Lugar",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Por favor asegúrate de que el presentador/a que deseas asignar al evento no exista en nuestro sistema antes de crearlo/a.",
                related_name="events",
                to="events.speaker",
                verbose_name="Presentadores",
            ),
        ),
    ]
