# Generated by Django 5.1.9 on 2025-09-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0035_remove_event_event_end_date_alter_event_description_and_more"),
        ("places", "0019_alter_city_options_alter_place_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("literature", "Literatura"),
                    ("society", "Sociedad"),
                    ("environment", "Medio ambiente"),
                    ("science", "Ciencia"),
                    ("art", "Arte"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Temática",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                help_text="Por favor, asegúrate de que el/la organizador/a que deseas asignar al evento no exista en nuestro sistema antes de crearlo/a.",
                related_name="events",
                to="events.organizer",
                verbose_name="Organizadores",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.ForeignKey(
                help_text="Por favor, asegúrate de que el lugar que deseas asignar al evento no exista en nuestro sistema antes de crearlo.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="places.place",
                verbose_name="Lugar",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Por favor, asegúrate de que el/la presentador/a que deseas asignar al evento no exista en nuestro sistema antes de crearlo/a.",
                related_name="events",
                to="events.speaker",
                verbose_name="Presentadores",
            ),
        ),
    ]
