# Generated by Django 5.1.9 on 2025-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0036_alter_event_category_alter_event_organizers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source_id",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Event source ID",
            ),
        ),
    ]
