# Generated by Django 5.1.9 on 2025-09-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0037_event_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Used for bulk event syncs for book fairs and festivals",
                verbose_name="Hidden from home and future events",
            ),
        ),
    ]
