# Generated by Django 5.1.9 on 2025-09-12 00:49

from django.db import migrations

def migrate_filbo_id(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.filter(filbo_id__isnull=False):
        event.source_id = 'FILBO2025_' + event.filbo_id
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0038_event_is_hidden"),
    ]

    operations = [
        migrations.RunPython(migrate_filbo_id),
    ]
