# Generated by Django 5.1.9 on 2025-09-12 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0039_auto_20250911_1949"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="filbo_id",
        ),
    ]
