# Generated by Django 5.1.9 on 2025-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0040_remove_event_filbo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="source_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Event source ID",
            ),
        ),
    ]
