# Generated by Django 6.0.3 on 2026-04-08 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_alter_event_source_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.CharField(blank=True, choices=[('early_childhood', 'Primera infancia'), ('children', 'Niños y niñas'), ('young_adult', 'Adultos jóvenes'), ('adults', 'Adultos'), ('families', 'Familias'), ('professionals', 'Profesionales'), ('all_audiences', 'Todo público')], db_index=True, max_length=50, verbose_name='Público objetivo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Está destacado en home'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Used for bulk event syncs for book fairs and festivals', verbose_name='Está oculto en home'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_organizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_speakers', to=settings.AUTH_USER_MODEL),
        ),
    ]
