# Generated by Django 6.0.6 on 2026-06-25 13:07

import autoslug.fields
import events.models.event
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_event_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=events.models.event._event_slugify, unique=True, validators=[events.models.event.validate_slug_not_reserved]),
        ),
    ]
