version: "3.9"
services:
  db:
    build: "./docker-containers/db"
    ports:
      - "5032:5432"
  web:
    build: "./docker-containers/web"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - .docker_pip_cache:/root/.cache/pip
  webpack:
    build: "docker-containers/webpack"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
