# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 16:38
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        UnaccentExtension()
    ]
