# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 16:38
from __future__ import unicode_literals

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [UnaccentExtension()]
