# Generated by Django 2.0.13 on 2019-06-16 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/press-article', verbose_name='Background Image')),
                ('source_url', models.URLField(verbose_name='Enlace a la página del artítulo')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
            ],
            options={
                'verbose_name': 'Press article',
                'verbose_name_plural': 'Press articles',
            },
        ),
        migrations.AlterModelOptions(
            name='mediasource',
            options={'verbose_name': 'Media Source', 'verbose_name_plural': 'Media Sources'},
        ),
        migrations.AddField(
            model_name='mediasource',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Página web'),
        ),
        migrations.AddField(
            model_name='pressarticle',
            name='media_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='press_articles', to='news.MediaSource'),
        ),
    ]
