# Generated by Django 2.0.13 on 2019-07-26 01:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190722_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressarticle',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
