# Generated by Django 2.0.13 on 2019-07-26 01:18

from autoslug.settings import slugify as default_slugify
from django.db import migrations


def gen_slug(apps, schema_editor):
    PressArticle = apps.get_model('news', 'PressArticle')
    for article in PressArticle.objects.all():
        article.slug = default_slugify(article.title)
        article.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_pressarticle_slug'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
