# Generated by Django 2.0.13 on 2019-07-26 01:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190725_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressarticle',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='title', unique=True
            ),
        ),
    ]
