# Generated by Django 2.0.13 on 2019-07-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190725_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressarticle',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
