# Generated by Django 4.2.11 on 2025-03-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_pressarticle_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressarticle',
            name='media_source',
        ),
        migrations.DeleteModel(
            name='MediaSource',
        ),
        migrations.DeleteModel(
            name='PressArticle',
        ),
    ]
