# Generated by Django 2.0.13 on 2019-06-23 02:33

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190622_2133'),
        ('books', '0002_auto_20190616_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blog_posts',
            field=models.ManyToManyField(
                blank=True,
                related_name='books',
                to='blog.Post',
                verbose_name='Entradas de blog',
            ),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name', unique=True
            ),
        ),
        migrations.AlterField(
            model_name='author',
            name='speaker',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='book_author',
                to='events.Speaker',
            ),
        ),
    ]
