# Generated by Django 4.2.11 on 2024-03-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190722_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={
                'ordering': ['-created'],
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
