# Generated by Django 4.2.11 on 2025-03-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='press_articles',
        ),
    ]
