version: "3.9"
services:
  web:
    build: "./docker-containers/web"
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - .docker_pip_cache:/root/.cache/pip
  db:
    build: "./docker-containers/db"
    ports:
      - "5032:5432"
