version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-be:
    docker:
      - image: cimg/python:3.10.16-node
        environment:
          DJANGO_SECRET_KEY: 'secret'
          DATABASE_NAME: 'desparchado_test'
          DATABASE_USER: 'root'
          DATABASE_PASSWORD: ''
          DATABASE_HOST: 'localhost'
          DATABASE_PORT: '5433'
          DJANGO_SETTINGS_MODULE: 'desparchado.settings.test'
      - image: cimg/postgres:13.16-postgis
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: desparchado_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.10/site-packages
      - run:
          name: Install Dependencies
          command: |
            pip3 install -r requirements.txt
      - run:
          name: Run tests
          command: python -m pytest
workflows:
  test:
    jobs:
      - test-be
