# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Página web')),
                ('source_type', models.PositiveSmallIntegerField(choices=[(None, 'Unknown'), ('', 'Conferencia pública'), ('facebook_events', 'Facebook events page')], verbose_name='Tipo del recurso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
