# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsource',
            name='source_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (None, 'Unknown'),
                    (2, 'Custom website'),
                    (1, 'Facebook events page'),
                ],
                verbose_name='Tipo del recurso',
            ),
        ),
    ]
