# Generated by Django 5.1.7 on 2025-03-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180701_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventSource',
        ),
    ]
