# Generated by Django 5.1.9 on 2025-09-23 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0003_delete_eventsource"),
        ("specials", "0004_alter_special_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpreadsheetSync",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "spreadsheet_id",
                    models.CharField(max_length=255, verbose_name="Spreadsheet ID"),
                ),
                ("worksheet_number", models.IntegerField(default=0)),
                (
                    "event_id_field",
                    models.CharField(
                        choices=[
                            ("event_source_url", "Event URL"),
                            ("source_id", "Source ID"),
                        ],
                        help_text="Campo utilizado para encontrar eventos existentes durante la sincronización",
                        verbose_name="Unique Event ID",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="Hidden from home"),
                ),
                (
                    "special",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="specials.special",
                        verbose_name="Especial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spreadsheet Sync",
                "verbose_name_plural": "Spreadsheet Syncs",
                "unique_together": {("spreadsheet_id", "worksheet_number")},
            },
        ),
    ]
