# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 00:13
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='posts', verbose_name='Imagen')),
                ('content', models.TextField(default='', help_text='Puedes usar <a href="/markdown" target="_blank">Markdown</a> para dar formato al texto.', verbose_name='Contenido')),
                ('is_published', models.BooleanField(default=True, help_text='Indica si la entrada va a aparecer en la página', verbose_name='Está publicado')),
                ('is_approved', models.BooleanField(default=True, help_text='Campo de uso exclusivo para el administrador del sitio', verbose_name='Está aprobado')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
