# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-02 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(
                default='', max_length=255, verbose_name='Título secundario'
            ),
        ),
    ]
