# Generated by Django 2.0.13 on 2019-06-23 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_related_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_posts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
