# Generated by Django 2.0.13 on 2019-06-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190622_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by_desparchado',
            field=models.BooleanField(default=False, verbose_name='Está publicado a nombre de la plataforma'),
        ),
    ]
