# Generated by Django 4.2.11 on 2024-03-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_created_by_desparchado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
