# Generated by Django 3.1.4 on 2020-12-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0002_special_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': 'Special', 'verbose_name_plural': 'Specials'},
        ),
    ]
