# Generated by Django 4.2.11 on 2024-03-18 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0002_special_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': 'Special', 'verbose_name_plural': 'Specials'},
        ),
    ]
