# Generated by Django 5.1.7 on 2025-04-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0003_alter_special_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='subtitle',
            field=models.CharField(
                default='', max_length=500, verbose_name='Subtítulo'
            ),
        ),
    ]
