# Generated by Django 5.1.9 on 2025-10-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specials", "0004_alter_special_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="is_featured_on_homepage",
            field=models.BooleanField(
                default=False, verbose_name="Está destacado en home"
            ),
        ),
    ]
