# Generated by Django 5.1.9 on 2025-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specials", "0005_special_is_featured_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="special",
            name="featured_on_homepage_until",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Fecha y hora límite para mostrar este especial en el home",
            ),
        ),
    ]
