# Generated by Django 5.1.9 on 2025-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specials", "0006_special_featured_on_homepage_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="special",
            name="featured_on_homepage_until",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Dejar en blanco para mostrar indefinidamente",
                null=True,
                verbose_name="Fecha y hora límite para mostrar este especial en el home",
            ),
        ),
    ]
