# Generated by Django 3.1.8 on 2021-05-24 17:54

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFigure',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'token',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Por ejemplo, "Simón Bolívar"',
                        max_length=255,
                        verbose_name='Nombre corto',
                    ),
                ),
                (
                    'full_name',
                    models.CharField(
                        help_text='Por ejemplo, "Simón José Antonio de la Santísima Trinidad Bolívar de la Concepción y Ponte Palacios y Blanco"',
                        max_length=500,
                        verbose_name='Nombre completo',
                    ),
                ),
                (
                    'sources',
                    models.TextField(
                        blank=True, default='', verbose_name='Fuentes de la información'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='history/historical-figures',
                        verbose_name='Imagen',
                    ),
                ),
                (
                    'image_source_url',
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name='Enlace a la fuente de la imagen',
                    ),
                ),
                ('date_of_birth', models.DateTimeField(db_index=True)),
                (
                    'date_of_birth_precision',
                    models.CharField(
                        choices=[
                            ('year', 'Año'),
                            ('month', 'Mes'),
                            ('day', 'Día'),
                            ('hour', 'Hora'),
                            ('minute', 'Minuto'),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    'date_of_death',
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    'date_of_death_precision',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('year', 'Año'),
                            ('month', 'Mes'),
                            ('day', 'Día'),
                            ('hour', 'Hora'),
                            ('minute', 'Minuto'),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_historical_figures',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Creado por',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Personaje histórico',
                'verbose_name_plural': 'Personajes históricos',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'token',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[('quote', 'Cita')],
                        db_index=True,
                        max_length=15,
                        null=True,
                    ),
                ),
                ('text', models.TextField(verbose_name='Texto')),
                (
                    'location_name',
                    models.CharField(blank=True, default='', max_length=500),
                ),
                (
                    'sources',
                    models.TextField(
                        blank=True, default='', verbose_name='Fuentes de la información'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='history/posts',
                        verbose_name='Imagen',
                    ),
                ),
                (
                    'image_source_url',
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name='Enlace a la fuente de la imagen',
                    ),
                ),
                (
                    'post_date',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='p. ej. 23/11/2019 18:00 (opcional)',
                        null=True,
                        verbose_name='Fecha de publicación',
                    ),
                ),
                (
                    'post_date_precision',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('year', 'Año'),
                            ('month', 'Mes'),
                            ('day', 'Día'),
                            ('hour', 'Hora'),
                            ('minute', 'Minuto'),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_history_posts',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Creado por',
                    ),
                ),
                (
                    'historical_figure',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='written_posts',
                        to='history.historicalfigure',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'token',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                (
                    'description',
                    models.TextField(
                        blank=True, default='', verbose_name='Descripción'
                    ),
                ),
                (
                    'sources',
                    models.TextField(
                        blank=True, default='', verbose_name='Fuentes de la información'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='history/events',
                        verbose_name='Imagen',
                    ),
                ),
                (
                    'image_source_url',
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name='Enlace a la fuente de la imagen',
                    ),
                ),
                (
                    'event_date',
                    models.DateTimeField(
                        db_index=True,
                        help_text='p. ej. 23/11/2019 16:40',
                        verbose_name='Fecha del evento',
                    ),
                ),
                (
                    'event_date_precision',
                    models.CharField(
                        choices=[
                            ('year', 'Año'),
                            ('month', 'Mes'),
                            ('day', 'Día'),
                            ('hour', 'Hora'),
                            ('minute', 'Minuto'),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    'location_name',
                    models.CharField(blank=True, default='', max_length=500),
                ),
                (
                    'event_end_date',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text='p. ej. 23/11/2019 18:00 (opcional)',
                        null=True,
                        verbose_name='Fecha final del evento',
                    ),
                ),
                (
                    'event_end_date_precision',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('year', 'Año'),
                            ('month', 'Mes'),
                            ('day', 'Día'),
                            ('hour', 'Hora'),
                            ('minute', 'Minuto'),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='created_history_events',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Creado por',
                    ),
                ),
                (
                    'historical_figures',
                    models.ManyToManyField(
                        blank=True,
                        related_name='history_events',
                        to='history.HistoricalFigure',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Evento histórico',
                'verbose_name_plural': 'Eventos históricos',
            },
        ),
    ]
