# Generated by Django 3.1.8 on 2021-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfigure',
            options={
                'ordering': ['name'],
                'verbose_name': 'Personaje histórico',
                'verbose_name_plural': 'Personajes históricos',
            },
        ),
        migrations.AlterField(
            model_name='historicalfigure',
            name='name',
            field=models.CharField(
                db_index=True,
                help_text='Por ejemplo, "Simón Bolívar"',
                max_length=255,
                verbose_name='Nombre corto',
            ),
        ),
    ]
