# Generated by Django 3.1.10 on 2021-06-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20210610_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalfigure',
            name='full_name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Por ejemplo, "Simón José Antonio de la Santísima Trinidad Bolívar de la Concepción y Ponte Palacios y Blanco"',
                max_length=500,
                verbose_name='Nombre completo',
            ),
        ),
    ]
