# Generated by Django 3.1.10 on 2021-06-15 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20210611_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={
                'ordering': ['-event_date'],
                'verbose_name': 'Evento histórico',
                'verbose_name_plural': 'Eventos históricos',
            },
        ),
        migrations.AddField(
            model_name='historicalfigure',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=15),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
