# Generated by Django 3.1.12 on 2021-07-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20210615_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[('quote', 'Cita'), ('Travel', 'Viaje')],
                db_index=True,
                max_length=15,
                null=True,
            ),
        ),
    ]
