# Generated by Django 4.2.11 on 2024-03-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20210723_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('quote', 'Cita'),
                    ('Travel', 'Viaje'),
                    ('marriage', 'Matrimonio'),
                    ('loss', 'Pérdida de un ser querido'),
                ],
                db_index=True,
                max_length=15,
                null=True,
            ),
        ),
    ]
