# Generated by Django 5.1.9 on 2025-06-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0009_alter_post_options_alter_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_end_date_precision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("year", "Año"),
                    ("month", "Mes"),
                    ("day", "Día"),
                    ("hour", "Hora"),
                    ("minute", "Minuto"),
                ],
                default="day",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Enlace a la fuente de la imagen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="group",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Enlace a la fuente de la imagen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalfigure",
            name="date_of_death_precision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("year", "Año"),
                    ("month", "Mes"),
                    ("day", "Día"),
                    ("hour", "Hora"),
                    ("minute", "Minuto"),
                ],
                default="day",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfigure",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Enlace a la fuente de la imagen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="image_source_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Enlace a la fuente de la imagen"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="post_date_precision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("year", "Año"),
                    ("month", "Mes"),
                    ("day", "Día"),
                    ("hour", "Hora"),
                    ("minute", "Minuto"),
                ],
                default="day",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quote", "Cita"),
                    ("Travel", "Viaje"),
                    ("marriage", "Matrimonio"),
                    ("loss", "Pérdida de un ser querido"),
                ],
                db_index=True,
                default="",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
