# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingOfSnarkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HuntingOfSnarkCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('public_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.HuntingOfSnarkCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='huntingofsnarkgame',
            name='criteria_ids',
        ),
        migrations.AddField(
            model_name='huntingofsnarkgame',
            name='criteria',
            field=models.ManyToManyField(to='games.HuntingOfSnarkCriteria'),
        ),
    ]
