# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 02:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190108_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huntingofsnarkcategory',
            options={
                'ordering': ('order',),
                'verbose_name': 'Hunting Of Snark Category',
                'verbose_name_plural': 'Hunting Of Snark Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='huntingofsnarkcriteria',
            options={'ordering': ('public_id',)},
        ),
        migrations.AddField(
            model_name='huntingofsnarkcategory',
            name='order',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='huntingofsnarkcriteria',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='criteria',
                to='games.HuntingOfSnarkCategory',
            ),
        ),
        migrations.AlterField(
            model_name='huntingofsnarkgame',
            name='player_name',
            field=models.CharField(
                blank=True,
                help_text='Su nombre o el nombre de su amigo con el que quiere jugar',
                max_length=255,
                verbose_name='Juego para',
            ),
        ),
    ]
