# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 23:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_huntingofsnarkgame_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huntingofsnarkgame',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='huntingofsnarkgame',
            name='total_points',
            field=models.IntegerField(help_text='Número de libros por leer', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Cantidad de criterios'),
        ),
    ]
