# Generated by Django 4.2.11 on 2024-03-18 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190209_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingofsnarkcriteria',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='criteria', to='games.huntingofsnarkcategory'),
        ),
        migrations.AlterField(
            model_name='huntingofsnarkgame',
            name='player_name',
            field=models.CharField(blank=True, help_text='Tu nombre o el nombre del amigo con el que quieres jugar', max_length=255, verbose_name='Juego para'),
        ),
    ]
